### ISSUE TITLE
Unrecognized Compressed Fluid In JEI

### ISSUE THREAD

**Issue by InsomniaKitten** [asiekierka/PrestonMC#7]
**Preston version:** [0.3.3](https://minecraft.curseforge.com/projects/preston/files/2534960)
**Forge version:** [1.12.2-14.23.2.2618](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.2.2618/forge-1.12.2-14.23.2.2618-changelog.txt)

There is a strange ItemStack listed under Preston in JEI, presumably a fluid, judging from the crashes produced by interacting with it. Crashes can be reproduced by attempting to view the recipe of the item in JEI, and by attempting to place the item in-world.

**Item tooltip:**

![tooltip](https://i.imgur.com/MFsQPt0.png)

**Crash from attempting to view compression recipe:**  [pastebin/XHxi2DAV](https://pastebin.com/raw/XHxi2DAV)
**Crash from attempting to place in-world:** [pastebin/YxFdwvjq](https://pastebin.com/raw/YxFdwvjq)

**Comment by asiekierka** [comment]
Hm. Bug!

**Comment by asiekierka** [comment]
Fixed in 0.3.4.
