### ISSUE TITLE
JEI tabs

### ISSUE THREAD

**Issue by pupnewfster** [asiekierka/PrestonMC#8]
This is not a major issue, just makes the JEI tab look a bit worse.

If you are looking at the recipe for a base block (say stone) it still has the tab for the Isochoric Compressor with no recipe displayed (because there is no recipe). I suggest when there is no recipe that the tab should be hidden.

Version: Preston 0.3.3

**Comment by asiekierka** [comment]
Fixed in 0.3.4.
