### ISSUE TITLE
Compressed Air?

### ISSUE THREAD

**Issue by Awec4** [asiekierka/PrestonMC#9]
https://imgur.com/a/zqWvC
Clicking on the Isochoric Compressor tab for the compressed air crashes Minecraft.
In addition to this it seems that although I'm using the whitelist, compressed blocks for blocks not on the whitelist are still generated, just without recipes, which seems strange to me.

**Comment by asiekierka** [comment]
FIxed (well, the part where Compressed Air even exists) in 0.3.4.

>In addition to this it seems that although I'm using the whitelist, compressed blocks for blocks not on the whitelist are still generated, just without recipes, which seems strange to me.

The blocks aren't really "generated". There is one block and one item which can technically "contain" any block in the game; so, in theory alone, compressed blocks for all blocks in the game exist at any given time.
